### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by mycold** [hyr0318/MaterialNews-Mvp#1]
04-06 14:17:13.670 21387-21409/com.github.hyr0318.materialnews_mvp E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
                                                                                     Process: com.github.hyr0318.materialnews_mvp, PID: 21387
                                                                                     java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                                      Caused by: java.lang.VerifyError: Rejecting class org.jsoup.parser.HtmlTreeBuilderState$7 because it failed compile-time verification (declaration of 'org.jsoup.parser.HtmlTreeBuilderState$7' appears in /data/app/com.github.hyr0318.materialnews_mvp-1/base.apk)
                                                                                         at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:244)
                                                                                         at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:50)
                                                                                         at org.jsoup.parser.Parser.parseInput(Parser.java:30)
                                                                                         at org.jsoup.helper.DataUtil.parseByteData(DataUtil.java:104)
                                                                                         at org.jsoup.helper.HttpConnection$Response.parse(HttpConnection.java:653)
                                                                                         at org.jsoup.helper.HttpConnection.get(HttpConnection.java:217)
                                                                                         at com.github.hyr0318.materialnews_mvp.model.TuwenModelImpl$1.call(TuwenModelImpl.java:50)
                                                                                         at com.github.hyr0318.materialnews_mvp.model.TuwenModelImpl$1.call(TuwenModelImpl.java:48)
                                                                                         at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                                         at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                                         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by mycold** [comment]
点击每日图文时出现该错误

**Comment by i91h1r** [comment]
@mycold 这个还没有解决
